### ISSUE TITLE
Celestia RPC client

### ISSUE THREAD

**Issue by joroshiba** [astriaorg/astria#11]
Update or replace rs-cnc with something with uses the Celestia Node JSON-RPC

Some prior work from Celestia:
https://github.com/rollkit/celestia-openrpc/pull/4/files

**Comment by joroshiba** [comment]
There is a client code generator for rust using the open rpc generator: https://www.npmjs.com/package/@open-rpc/generator-client

Can't speak to whether it generates anything worthwhile, but it is likely a good starting point.

**Comment by SuperFluffy** [comment]
I have started working on this in branch https://github.com/astriaorg/astria/tree/celestia_json_rpc (note that at the time of this writing the referenced `celestia-node:test` image is a local image where I forked `celestia-node:v0.10.1` to add `curl` and `jq` to the image so that I can get the genesis hash from celestia-app).

Using [jsonrpsee_proc_macros](https://docs.rs/jsonrpsee-proc-macros/0.18.2/jsonrpsee_proc_macros/index.html) it's actually pretty straight forward to generate the relevant Rust boilerplate to interact with the celestia json RPC.

I am currently stuck on registering a token with the node that I can use to interact with the permissioned JSON RPC methods. I performed the following steps:

```sh
# enter the container running celestia-node
> kubectl exec --stdin --tty -n test sequencer-relayer-environment-deployment-6789699b69-fsddm -c celestia-bridge -- /bin/sh
# try to create a token with write permissions, keeping all other arguments the same as when starting the celestia bridge node
$ genesis_hash=$(curl -s -S -X GET "http://127.0.0.1:26657/block?height=1" | jq -er '.result.block_id.hash')
$ export CELESTIA_CUSTOM="test:$genesish_hash"
$ celestia bridge auth write --node.store home_dir/bridge --keyring.accname $validator_key_name
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJwdWJsaWMiLCJyZWFkIiwid3JpdGUiXX0.gdHm9UFlPcUS-aP13klGWqieX89q99MrisRgZzCGGRA
```
Inserting that token into the header map as `Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJwdWJsaWMiLCJyZWFkIiwid3JpdGUiXX0.gdHm9UFlPcUS-aP13klGWqieX89q99MrisRgZzCGGRA` gives permission issues. This is from the celestia-node logs:
```
2023-05-26T22:59:23.262Z	WARN	rpc	go-jsonrpc@v0.1.9/handler.go:334	error in RPC call to 'state.SubmitPayForBlob': missing permission to invoke 'SubmitPayForBlob' (need 'write'):
    github.com/filecoin-project/go-jsonrpc/auth.PermissionedProxy.func1
        /go/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.9/auth/auth.go:65
```

**Comment by steezeburger** [comment]
Relevant issue
https://github.com/celestiaorg/celestia-node/issues/2321
