### ISSUE TITLE
Sequencer: Log contents of block production

### ISSUE THREAD

**Issue by jbowen93** [astriaorg/astria#128]

**Comment by joroshiba** [comment]
We want a pretty level of logging likely in sequencer relayer which can provide a breakdown of the following information:

- Who the tendermint proposer was for the block
- Each secondary chain id included and number of txs included
- DA block height the data is stored at

This ideally should be done in such a way that it looks ✨pretty✨ and can be filtered to in order to display this information in a demo environment.
