### ISSUE TITLE
composer: refetch nonce on transaction failure due to invalid nonce

### ISSUE THREAD

**Issue by itamarreif** [astriaorg/astria#293]
We currently do not handle sequencer transactions failing due to incorrect nonce. This should be addressed so that rollup transactions don't get lost due to failed submission.

The channel communication to `Executor` that will be implemented in #292 will allow the `Executor` to submit transactions sequentially. This will allow the `Executor` reason about the nonce of one transaction at a time, rather than multiple pending submissions.

With these changes, nonces can be managed by having an `Option<Nonce>` in the `Executor` upon constructing an `Unsigned` from a `Vec<Action>` :
1. If nonce is `None`, fetch latest nonce from the sequencer
2. Return current nonce and increment for next time

When a `Signed` transaction submission fails due to an invalid nonce, reset the nonce to `None` and reprocess the `Vec<Action>`. This will result in the correct latest nonce being fetched from the sequencer, constructing a new `Unsigned`, signing it and submitting.

**Comment by emhane** [comment]
nice issue! adding the several related issues into a task list in the root issue would make it easier to follow along.

to me it then seems like [this local value of the sequencer's nonce](https://github.com/astriaorg/astria/blob/a889ca6af6adbea28788cd4f438fe3f4f4be3be4/crates/astria-composer/src/searcher/mod.rs#L70-L71) could be removed in favour of [fetching the global value of the nonce](https://github.com/astriaorg/astria/blob/a889ca6af6adbea28788cd4f438fe3f4f4be3be4/crates/astria-composer/src/searcher/mod.rs#L276-L282)? that way, in the future, transitioning to a relationship between sequencer and composer that isn't 1-1 would be a piece of cake. for example if two node operators on two different rollups each run their own composer, but use the same sequencer. the local value otherwise always risks being out of sync.

**Comment by emhane** [comment]
oh no, hang on, the [sequencer key](https://github.com/astriaorg/astria/blob/a889ca6af6adbea28788cd4f438fe3f4f4be3be4/crates/astria-composer/src/searcher/mod.rs#L68-L69) is for a sequencer account, right. then it's still efficient to use the local tracking nonce, so long as not many composers share a sequencer account, which I think we can assume they won't.
