### ISSUE TITLE
remove gossipnet from conductor

### ISSUE THREAD

**Issue by joroshiba** [astriaorg/astria#332]
Based on discussion in #325, where we have opted for option 1.

We want to strip out the gossipnet, and instead rely on a full node of the sequencer to read blocks. This is similar to what we are doing in `sequencer-relayer` to read new blocks off of proposing chains. We should do this using a [cometbft websocket subscription](https://docs.cometbft.com/v0.37/core/subscription).

Note: we may need to handle network retry logic in here in case a packet goes missing, and ws connection loses a block.

**Comment by emhane** [comment]
before updating events cometbft validates the block. this means blocks received over the web socket always point to the canonical chain, that is their parent block is the soft block.

apply block tries to validate block and last publishes events
https://github.com/astriaorg/cometbft/blob/342404c9011137cb0e9a4abfd9fa1fc2f9ca889e/state/execution.go#L182-L264

validation checks our equivalent to head block's parent block hash with our equivalent to soft block hash
https://github.com/astriaorg/cometbft/blob/342404c9011137cb0e9a4abfd9fa1fc2f9ca889e/state/validation.go#L45-L51

the state where last block hash is taken from is block applied before this one
https://github.com/astriaorg/cometbft/blob/342404c9011137cb0e9a4abfd9fa1fc2f9ca889e/state/execution.go#L234-L238

so event publisher publishes validated block
https://github.com/astriaorg/cometbft/blob/342404c9011137cb0e9a4abfd9fa1fc2f9ca889e/state/execution.go#L259-L261

this constrains the way to handle incoming blocks.

it means, assuming we trust the validator we are connected to via web socket, all blocks that are received at head height point to the soft block. further this implies, if a child to any of the head blocks is received it will certainly finalise the soft block. also by single slot finality it implies that if head block N+1 is lost but we see its child N+2 and grandchild N+3, we can deduce that the parent block hash in N+2 is the final head.

also we know that any blocks that will become part of the canonical chain, will pass conversion from tendermint block response to `SequencerBlockData` which verifies commit to the rollup data, because all shared-sequencer validators do the same checks on the data before prevoting the block. by this we know that all blocks in the canonical chain will have valid commitment to rollup data, hence with the above example, if N+2 successfully passes the conversion to `SequencerBlockData` we know when N+3 comes that the parent block of N+2 had valid commitment to rollup data.

https://github.com/astriaorg/astria/blob/main/specs/sequencer-app.md#processproposal

**Comment by emhane** [comment]
...trust the validator (or sequencer without validator), and trust the connection! add TLS to web socket connection if conductor and sequencer not intended to run on localhost if?

**Comment by emhane** [comment]
can we divide this issue into two parts: (i) removing gossipnet and (ii) adding web socket ? I'd start working on adding a web socket to conductor and encrypting the messages with this library https://crates.io/crates/tokio-native-tls or some other library.
