### ISSUE TITLE
Pull out services' configs to its own crate `astria-config`

### ISSUE THREAD

**Issue by steezeburger** [astriaorg/astria#398]
After doing the work for https://github.com/astriaorg/astria/pull/387, we realized it's a good idea to pull out configuration into its own crate `astria-config`

**Comment by dereksione** [comment]
Assigning this to me if that is okay @steezeburger

**Comment by dereksione** [comment]
Current thoughts (from the composer discussion on 09-21-2023: the tests can just be a normal macro - the config creator is more involved and will probably involve creating a proc macro so that during compile time, it can expand into a serde de-serializer implementation such that the errors created can have behavior desirable to our config specifically (i.e. proper error messages automatically generated).
